"use client"

import type React from "react"
import { useEffect,useMemo,useState } from "react"
import Link from "next/link"
import type { DadGroup,Thread } from "@dadsconnect/shared"
import { ArrowLeftIcon,MessageSquareIcon,PlusIcon,UsersIcon } from "lucide-react"

export default function DiscussionsPage(){
 const [threads,setThreads]=useState<Thread[]>([]);const [groups,setGroups]=useState<DadGroup[]>([]);const [selectedGroup,setSelectedGroup]=useState("all");const [composerOpen,setComposerOpen]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null)
 const loadThreads=async()=>{setError(null);try{const query=selectedGroup==='all'?'':`?group_id=${encodeURIComponent(selectedGroup)}`;const response=await fetch('/api/threads'+query,{credentials:'include'});if(response.status===401){window.location.href='/login';return}const data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to load conversations');setThreads(data.threads||[])}catch(error){setError(error instanceof Error?error.message:'Failed to load conversations')}finally{setLoading(false)}}
 useEffect(()=>{void loadThreads()},[selectedGroup])
 useEffect(()=>{;(async()=>{const response=await fetch('/api/groups',{credentials:'include'});if(!response.ok)return;const data=await response.json();setGroups((data.groups||[]).filter((group:DadGroup)=>group.isMember))})()},[])
 const createDiscussion=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError(null);const form=new FormData(event.currentTarget);const payload={groupId:String(form.get('groupId')||''),title:String(form.get('title')||''),body:String(form.get('body')||'')};try{const response=await fetch('/api/threads',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Failed to ask the dads');setComposerOpen(false);setSelectedGroup(payload.groupId||'all');await loadThreads()}catch(error){setError(error instanceof Error?error.message:'Failed to ask the dads')}finally{setSaving(false)}}
 const visibleGroups=useMemo(()=>[{id:'all',name:'All my crews'} as Pick<DadGroup,'id'|'name'>,...groups],[groups])
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#f4f1e9] font-semibold text-[#667187]">Checking what the dads are talking about…</div>
 return <main className="min-h-screen bg-[#f4f1e9] text-[#10213d]"><div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 sm:py-10">
  <Link href="/feed" className="mb-7 inline-flex items-center gap-2 text-sm font-black text-[#667187]"><ArrowLeftIcon className="h-4 w-4"/>Crew hub</Link>
  <section className="relative mb-7 overflow-hidden rounded-[32px] bg-[#10213d] p-7 text-white shadow-[0_9px_0_#d7d0c4] sm:p-10"><div className="absolute -right-7 -top-10 h-40 w-40 rotate-12 rounded-[42px] bg-[#f5c85b]"/><p className="relative text-xs font-black tracking-[.18em] text-[#a8d8c6]">ASK THE DADS</p><h1 className="relative mt-3 max-w-2xl text-4xl font-black tracking-[-.045em] sm:text-5xl">You probably aren’t the only dad figuring it out.</h1><p className="relative mt-4 max-w-2xl text-lg leading-8 text-[#bdc8d8]">Ask the practical question, share what worked, admit what didn’t, or just see how another dad handled it.</p><button onClick={()=>setComposerOpen(current=>!current)} disabled={!groups.length} className="relative mt-7 inline-flex items-center gap-2 rounded-xl bg-[#f5c85b] px-5 py-3 font-black text-[#10213d] shadow-[0_4px_0_#bd922d] disabled:opacity-50"><PlusIcon className="h-4 w-4"/>{composerOpen?'Close question':'Ask the dads'}</button></section>
  {!groups.length&&<div className="mb-6 rounded-2xl border-2 border-[#d9d2c5] bg-white p-5"><strong>Join a crew before posting.</strong><p className="mt-1 text-sm text-[#667187]">Conversations live inside crews so the room stays relevant instead of becoming one giant public feed.</p><Link href="/groups" className="mt-3 inline-block font-black text-primary">Find a crew →</Link></div>}
  {error&&<div role="alert" className="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
  {composerOpen&&<form onSubmit={createDiscussion} className="mb-8 rounded-[28px] border-2 border-[#d9d2c5] bg-white p-5 shadow-[0_6px_0_rgba(16,33,61,.06)] sm:p-7"><p className="text-xs font-black tracking-[.16em] text-primary">START WITH THE REAL QUESTION</p><h2 className="mt-1 text-2xl font-black">What do you want another dad’s take on?</h2><div className="mt-5 grid gap-4 sm:grid-cols-[220px_1fr]"><label className="text-sm font-black">Which crew?<select name="groupId" required className="mt-2 h-12 w-full rounded-xl border-2 border-[#ddd8cf] bg-[#fbfaf7] px-3"><option value="">Choose a crew</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></label><label className="text-sm font-black">The question<input name="title" required maxLength={160} className="mt-2 h-12 w-full rounded-xl border-2 border-[#ddd8cf] bg-[#fbfaf7] px-4" placeholder="Anybody else dealing with…?"/></label></div><label className="mt-4 block text-sm font-black">Give the dads some context<textarea name="body" required maxLength={10000} rows={5} className="mt-2 w-full resize-none rounded-2xl border-2 border-[#ddd8cf] bg-[#fbfaf7] px-4 py-3" placeholder="What happened, what have you tried, and what kind of perspective would help?"/></label><button type="submit" disabled={saving} className="mt-4 rounded-xl bg-primary px-6 py-3 font-black text-white shadow-[0_3px_0_#173b93] disabled:opacity-50">{saving?'Posting…':'Put it to the crew →'}</button></form>}
  <div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-black tracking-[.16em] text-primary">THE CREW BOARD</p><h2 className="mt-1 text-2xl font-black">What dads are talking about</h2></div><select aria-label="Filter conversations by crew" value={selectedGroup} onChange={event=>setSelectedGroup(event.target.value)} className="h-11 rounded-full border-2 border-[#d7d1c6] bg-white px-4 text-sm font-black">{visibleGroups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></div>
  <section className="grid gap-4">{threads.map((thread,index)=>{const initials=(thread.author?.name||'DadConnect').split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();const reactionCount=thread.reactions?Object.values(thread.reactions).reduce((sum,value)=>sum+Number(value||0),0):0;return <article key={thread.id} className={`rounded-[26px] border-2 p-5 sm:p-6 ${index%5===0?'border-[#e4c35e] bg-[#fff8df]':'border-[#d9d2c5] bg-white'}`}><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#10213d] text-sm font-black text-white">{initials}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{thread.group&&<Link href={`/groups/${thread.group.id}/chat`} className="rounded-full bg-[#eef4ff] px-2.5 py-1 text-[11px] font-black text-primary">{thread.group.name}</Link>}<time className="text-xs font-semibold text-[#89919f]">{new Date(thread.ts).toLocaleString()}</time></div><h3 className="mt-2 text-xl font-black tracking-[-.02em]">{thread.title}</h3><p className="mt-3 whitespace-pre-wrap leading-7 text-[#5f6b7d]">{thread.body}</p><div className="mt-5 flex flex-wrap items-center gap-3 text-xs font-bold text-[#778196]"><span>{thread.author?.name||'DadConnect dad'}</span><span className="inline-flex items-center gap-1"><MessageSquareIcon className="h-3.5 w-3.5"/>Conversation</span>{reactionCount>0&&<span>👊 {reactionCount}</span>}</div></div></div></article>})}{!threads.length&&<div className="rounded-[28px] border-2 border-dashed border-[#d5cec2] bg-white/60 px-6 py-14 text-center"><MessageSquareIcon className="mx-auto h-8 w-8 text-primary"/><h2 className="mt-4 text-2xl font-black">Quiet crew board.</h2><p className="mx-auto mt-2 max-w-md text-[#667187]">That usually means somebody needs to go first. Ask something useful, specific, or real.</p>{groups.length>0&&<button onClick={()=>setComposerOpen(true)} className="mt-5 rounded-xl bg-primary px-5 py-3 font-black text-white">Ask the first question</button>}</div>}</section>
  <div className="mt-8 rotate-[.5deg] rounded-[24px] bg-[#a8d8c6] p-5 sm:p-6"><p className="text-xs font-black tracking-[.14em]">DADCONNECT RULE</p><p className="mt-2 text-xl font-black">Advice beats judgment. Experience beats pretending you know everything.</p></div>
 </div></main>
}
