"use client"

import { useCallback,useEffect,useRef,useState } from "react"
import Link from "next/link"
import { useParams,useRouter } from "next/navigation"
import type { DadGroup,GroupMessage,Meetup } from "@dadsconnect/shared"
import { CalendarDaysIcon,UsersIcon,SendIcon,ArrowLeftIcon } from "lucide-react"
import { getSupabaseBrowserClient } from "@/lib/supabase-client"

export default function GroupChatPage(){
 const params=useParams<{groupId:string}>();const router=useRouter();const groupId=params.groupId;const [group,setGroup]=useState<DadGroup|null>(null);const [messages,setMessages]=useState<GroupMessage[]>([]);const [meetups,setMeetups]=useState<Meetup[]>([]);const [userId,setUserId]=useState<string|null>(null);const [draft,setDraft]=useState("");const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [loadError,setLoadError]=useState<string|null>(null);const [sendError,setSendError]=useState<string|null>(null);const bottomRef=useRef<HTMLDivElement|null>(null)
 const loadMessages=useCallback(async()=>{setLoadError(null);const supabase=getSupabaseBrowserClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return false}const {data:membership,error:membershipError}=await supabase.from('group_members').select('group_id').eq('group_id',groupId).eq('user_id',user.id).maybeSingle();if(membershipError||!membership){setLoadError('Join this crew before opening its chat.');return false}const {data,error}=await supabase.from('group_messages').select(`*,profiles!group_messages_author_id_fkey(id,name,avatar_url)`).eq('group_id',groupId).order('created_at',{ascending:false}).limit(100);if(error)throw new Error(error.message||'Failed to load messages');setMessages((data||[]).slice().reverse().map(message=>({id:message.id,groupId:message.group_id,authorId:message.author_id,content:message.content,messageType:message.message_type as GroupMessage['messageType'],metadata:message.metadata as GroupMessage['metadata'],createdAt:message.created_at,author:message.profiles?{id:message.profiles.id,name:message.profiles.name,avatarUrl:message.profiles.avatar_url,city:null,state:null,bio:null,interests:[],kidsAges:[],createdAt:''}:undefined})));return true},[groupId,router])
 useEffect(()=>{let active=true;const supabase=getSupabaseBrowserClient();let channel:ReturnType<typeof supabase.channel>|null=null;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}if(!active)return;setUserId(user.id);const {data:groupRow,error:groupError}=await supabase.from('dad_groups').select('*').eq('id',groupId).maybeSingle();if(groupError||!groupRow){setLoadError(groupError?.message||'Crew not found.');setLoading(false);return}setGroup({id:groupRow.id,name:groupRow.name,description:groupRow.description,category:groupRow.category as DadGroup['category'],topics:groupRow.topics,city:groupRow.city,state:groupRow.state,visibility:groupRow.visibility as DadGroup['visibility'],memberCount:groupRow.member_count,createdBy:groupRow.created_by,createdAt:groupRow.created_at,isMember:true});try{const allowed=await loadMessages();if(!allowed||!active)return;const meetupResponse=await fetch(`/api/meetups?group_id=${groupId}`,{credentials:'include'});if(meetupResponse.ok){const meetupData=await meetupResponse.json();if(active)setMeetups(meetupData.meetups||[])}channel=supabase.channel(`group-chat-${groupId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'group_messages',filter:`group_id=eq.${groupId}`},()=>{void loadMessages()}).subscribe()}catch(error){setLoadError(error instanceof Error?error.message:'Failed to load chat')}finally{if(active)setLoading(false)}})();return()=>{active=false;if(channel)void supabase.removeChannel(channel)}},[groupId,loadMessages,router])
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth'})},[messages])
 const send=async(event:React.FormEvent)=>{event.preventDefault();const content=draft.trim();if(!content||sending)return;setSending(true);setSendError(null);try{const response=await fetch(`/api/groups/${groupId}/messages`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Failed to send message');setDraft('');setMessages(current=>current.some(item=>item.id===data.message.id)?current:[...current,data.message].slice(-100))}catch(error){setSendError(error instanceof Error?error.message:'Failed to send message')}finally{setSending(false)}}
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#f4f1e9] font-semibold text-[#667187]">Opening the crew room…</div>
 return <main className="min-h-screen bg-[#f4f1e9] text-[#10213d]"><div className="mx-auto flex min-h-screen w-full max-w-6xl flex-col px-0 sm:px-4">
  <header className="sticky top-0 z-20 border-b-2 border-[#ddd6ca] bg-[#f4f1e9]/95 px-4 py-4 backdrop-blur sm:mt-4 sm:rounded-t-[28px] sm:border-x-2 sm:border-t-2">
   <Link href="/groups" className="inline-flex items-center gap-2 text-xs font-black text-[#667187]"><ArrowLeftIcon className="h-3 w-3"/>All crews</Link><div className="mt-3 flex items-end justify-between gap-3"><div><div className="flex items-center gap-2"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#f5c85b] text-xl">👊</span><div><h1 className="text-xl font-black sm:text-2xl">{group?.name||'Crew room'}</h1><p className="flex items-center gap-1 text-xs font-bold text-[#778196]"><UsersIcon className="h-3 w-3"/>{group?.memberCount||0} dads • live crew chat</p></div></div></div><Link href={`/meetups/create?groupId=${groupId}`} className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-black text-white shadow-[0_3px_0_#173b93]"><CalendarDaysIcon className="h-4 w-4"/><span className="hidden sm:inline">Make a plan</span><span className="sm:hidden">Plan</span></Link></div>
  </header>
  {loadError&&<div role="alert" className="m-4 rounded-2xl border border-amber-200 bg-[#fff8df] p-4 text-sm font-semibold text-[#765b16]">{loadError}</div>}
  <section className="border-b-2 border-[#e0dad0] bg-white px-4 py-5 sm:border-x-2"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-black tracking-[.16em] text-primary">TURN TALK INTO REAL LIFE</p><h2 className="mt-1 font-black">Plans with this crew</h2></div><Link href={`/meetups/create?groupId=${groupId}`} className="text-xs font-black text-primary">+ Plan one</Link></div>{meetups.length?<div className="flex gap-3 overflow-x-auto pb-1">{meetups.slice(0,4).map(meetup=><Link key={meetup.id} href={`/meetups/${meetup.id}`} className="min-w-[230px] rounded-2xl border-2 border-[#e4c35e] bg-[#fff8df] p-4"><strong className="block text-sm">{meetup.title}</strong><span className="mt-1 block text-xs font-semibold text-[#697386]">{new Date(meetup.startTime).toLocaleString()} • {meetup.currentAttendees} going</span></Link>)}</div>:<div className="rounded-2xl bg-[#faf8f3] p-4 text-sm text-[#697386]">Nothing on the calendar yet. If the chat keeps saying “we should,” make it real.</div>}</section>
  <section className="flex-1 space-y-3 overflow-y-auto bg-[#eef1f4] px-4 py-6 sm:border-x-2 sm:border-[#ddd6ca]">{!messages.length&&!loadError&&<div className="mx-auto mt-12 max-w-sm rounded-[26px] border-2 border-dashed border-[#cfc9bf] bg-white p-8 text-center"><span className="text-4xl">💬</span><h2 className="mt-3 text-xl font-black">Somebody has to go first.</h2><p className="mt-2 text-sm leading-6 text-[#697386]">Ask a question, share a dad win, or get a plan moving.</p></div>}{messages.map(message=>{const own=message.authorId===userId;return <article key={message.id} className={`max-w-[86%] rounded-[22px] px-4 py-3 shadow-sm sm:max-w-[70%] ${own?'ml-auto rounded-br-md bg-primary text-white':'rounded-bl-md border border-[#e1ddd6] bg-white text-[#10213d]'}`}>{!own&&<p className="mb-1 text-xs font-black text-primary">{message.author?.name||'DadConnect dad'}</p>}<p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p><time className={`mt-1 block text-[10px] font-semibold ${own?'text-blue-100':'text-[#8a92a0]'}`}>{new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></article>})}<div ref={bottomRef}/></section>
  <form onSubmit={send} className="sticky bottom-0 border-t-2 border-[#ddd6ca] bg-white p-3 sm:mb-4 sm:rounded-b-[28px] sm:border-x-2 sm:border-b-2 sm:p-4">{sendError&&<p role="alert" className="mb-2 rounded-xl bg-red-50 p-2 text-sm text-red-700">{sendError}</p>}<div className="flex items-end gap-2"><textarea value={draft} onChange={event=>setDraft(event.target.value)} maxLength={4000} rows={2} className="min-h-12 flex-1 resize-none rounded-2xl border-2 border-[#ddd8cf] bg-[#fbfaf7] px-4 py-3 text-sm outline-none focus:border-primary" placeholder="Say something to the crew…"/><button type="submit" aria-label="Send message" disabled={sending||!draft.trim()||Boolean(loadError)} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-primary text-white shadow-[0_3px_0_#173b93] disabled:bg-[#c9c5bd] disabled:shadow-none"><SendIcon className="h-5 w-5"/></button></div></form>
 </div></main>
}
