'use client'

import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import type { DadGroup } from '@dadsconnect/shared'
import { ArrowLeftIcon,MapPinIcon,UsersIcon,MessageSquareIcon,CalendarDaysIcon,PlusIcon } from 'lucide-react'

const categories=[['all','All crews','👊'],['support','Support','🤝'],['sports','Sports','🏀'],['activities','Activities','🛝'],['local','Local','📍'],['interests','Interests','🧰']] as const
const accents:Record<string,string>={support:'bg-[#dff2e9]',sports:'bg-[#fff0d8]',activities:'bg-[#e8f1ff]',local:'bg-[#eee9ff]',interests:'bg-[#f0ede7]'}

export default function GroupsPage(){
 const [groups,setGroups]=useState<DadGroup[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [filter,setFilter]=useState('all');const [joining,setJoining]=useState<string|null>(null)
 const loadGroups=async()=>{setError(null);try{const response=await fetch('/api/groups',{credentials:'include'});if(response.status===401){window.location.href='/login';return}const data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to load groups');setGroups(data.groups||[])}catch(error){setError(error instanceof Error?error.message:'Failed to load groups')}finally{setLoading(false)}}
 useEffect(()=>{void loadGroups()},[])
 const joinGroup=async(groupId:string)=>{setJoining(groupId);setError(null);try{const response=await fetch(`/api/groups/${groupId}/join`,{method:'POST',credentials:'include'});if(response.status===401){window.location.href='/login';return}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Failed to join group');await loadGroups()}catch(error){setError(error instanceof Error?error.message:'Failed to join group')}finally{setJoining(null)}}
 const filteredGroups=useMemo(()=>filter==='all'?groups:groups.filter(group=>group.category===filter),[filter,groups]);const joined=groups.filter(group=>group.isMember);const publicCount=groups.filter(group=>group.visibility==='public').length
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#f4f1e9] font-semibold text-[#667187]">Finding your crews…</div>
 return <main className="min-h-screen bg-[#f4f1e9] text-[#10213d]">
  <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 sm:py-10">
   <Link href="/feed" className="mb-7 inline-flex items-center gap-2 text-sm font-black text-[#667187] hover:text-primary"><ArrowLeftIcon className="h-4 w-4"/>Crew hub</Link>
   <section className="relative mb-8 overflow-hidden rounded-[32px] bg-[#10213d] p-7 text-white shadow-[0_9px_0_#d7d0c4] sm:p-10">
    <div className="absolute -right-5 -top-10 h-36 w-36 rotate-12 rounded-[38px] bg-[#f5c85b]"/><p className="relative text-xs font-black tracking-[.18em] text-[#f5c85b]">FIND YOUR PEOPLE</p><h1 className="relative mt-3 max-w-2xl text-4xl font-black tracking-[-.045em] sm:text-5xl">A good crew makes dad life lighter.</h1><p className="relative mt-4 max-w-2xl text-lg leading-8 text-[#bdc8d8]">Join around a stage, neighborhood, hobby, or something you are figuring out. The point is not collecting groups — it is finding dads you will actually talk to.</p><div className="relative mt-7 flex flex-wrap gap-3"><Link href="/groups/create" className="inline-flex items-center gap-2 rounded-xl bg-[#f5c85b] px-5 py-3 font-black text-[#10213d] shadow-[0_4px_0_#bd922d]"><PlusIcon className="h-4 w-4"/>Start a crew</Link>{joined.length>0&&<Link href={`/groups/${joined[0].id}/chat`} className="rounded-xl border-2 border-[#53627a] px-5 py-3 font-black text-white">Jump back into chat</Link>}</div>
   </section>
   <section className="mb-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border-2 border-[#ddd6ca] bg-white p-4"><span className="text-xs font-black text-[#778196]">YOUR CREWS</span><strong className="mt-1 block text-3xl">{joined.length}</strong></div><div className="rounded-2xl border-2 border-[#ddd6ca] bg-white p-4"><span className="text-xs font-black text-[#778196]">OPEN TO JOIN</span><strong className="mt-1 block text-3xl">{publicCount}</strong></div><div className="rounded-2xl bg-[#a8d8c6] p-4"><span className="text-xs font-black">THE GOAL</span><strong className="mt-1 block text-lg leading-6">Find a few solid dads, not a follower count.</strong></div></section>
   <div className="mb-8 flex gap-2 overflow-x-auto pb-2">{categories.map(([key,label,emoji])=><button key={key} onClick={()=>setFilter(key)} className={`whitespace-nowrap rounded-full border-2 px-4 py-2 text-sm font-black transition ${filter===key?'border-[#10213d] bg-[#10213d] text-white':'border-[#d7d1c6] bg-white text-[#5d687b] hover:border-primary'}`}>{emoji} {label}</button>)}</div>
   {error&&<div role="alert" className="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
   <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filteredGroups.map((group,index)=><article key={group.id} className={`flex min-h-[330px] flex-col rounded-[28px] border-2 border-[#d9d2c5] p-6 shadow-[0_6px_0_rgba(16,33,61,.06)] ${index%4===1?'bg-[#fff8df]':'bg-white'}`}>
    <div className="mb-5 flex items-start justify-between gap-4"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl text-2xl ${accents[group.category]||'bg-[#f0ede7]'}`}>{group.category==='sports'?'🏀':group.category==='activities'?'🛝':group.category==='local'?'📍':group.category==='support'?'🤝':'🧰'}</div><div className="text-right"><strong className="block text-2xl">{group.memberCount}</strong><span className="text-xs font-bold text-[#778196]">dads</span></div></div>
    <div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#eef4ff] px-2.5 py-1 text-[11px] font-black uppercase tracking-wide text-primary">{group.category}</span>{group.visibility==='private'&&<span className="rounded-full bg-[#f0ede7] px-2.5 py-1 text-[11px] font-black">PRIVATE</span>}</div><h2 className="mt-3 text-2xl font-black tracking-[-.025em]">{group.name}</h2>{group.city&&<p className="mt-1 flex items-center gap-1 text-xs font-bold text-[#778196]"><MapPinIcon className="h-3 w-3"/>{group.city}{group.state?`, ${group.state}`:''}</p>}<p className="mt-3 line-clamp-3 flex-1 leading-7 text-[#667187]">{group.description||'A DadConnect crew waiting for its next conversation.'}</p><div className="my-4 flex flex-wrap gap-1.5">{group.topics.slice(0,3).map(topic=><span key={topic} className="rounded-full border border-[#dce2ea] bg-[#fafbfc] px-2 py-1 text-xs font-bold text-[#697386]">{topic}</span>)}</div>
    {group.isMember?<div className="grid grid-cols-2 gap-2"><Link href={`/groups/${group.id}/chat`} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-3 py-3 text-sm font-black text-white shadow-[0_3px_0_#173b93]"><MessageSquareIcon className="h-4 w-4"/>Chat</Link><Link href={`/meetups/create?groupId=${group.id}`} className="inline-flex items-center justify-center gap-2 rounded-xl border-2 border-[#10213d] px-3 py-3 text-sm font-black"><CalendarDaysIcon className="h-4 w-4"/>Plan</Link></div>:<button onClick={()=>joinGroup(group.id)} disabled={joining===group.id||group.visibility==='private'} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-black text-white shadow-[0_3px_0_#173b93] disabled:bg-[#c9c5bd] disabled:shadow-none"><UsersIcon className="h-4 w-4"/>{joining===group.id?'Joining…':group.visibility==='private'?'Private crew':'Join this crew'}</button>}
   </article>)}</div>
   {!filteredGroups.length&&<div className="rounded-[30px] border-2 border-dashed border-[#d5cec2] bg-white/60 px-6 py-14 text-center"><span className="text-4xl">👊</span><h2 className="mt-4 text-2xl font-black">No crew here yet.</h2><p className="mx-auto mt-2 max-w-md text-[#667187]">That is an opening, not a dead end. Start one around a place, parenting stage, activity, or shared interest.</p><Link href="/groups/create" className="mt-6 inline-block rounded-xl bg-primary px-6 py-3 font-black text-white shadow-[0_3px_0_#173b93]">Start the first crew</Link></div>}
  </div>
 </main>
}
